version: "3.8"

services:
  redis:
    image: "redis:latest"
    container_name: "redis"
    ports:
      - "6379:6379"
    restart: always
    
  fastapi:
    build: .
    container_name: api
    ports:
      - "8000:8000"
    depends_on:
      - redis
  
  worker:
    build: .
    container_name: celery_worker
    environment:
      - CELERY_BROKER_URL=redis://redis:6379/0
      - CELERY_BACKEND_URL=redis://redis:6379/0
    command: ["poetry", "run", "celery", "-A", "tasks.celery", "worker", "--loglevel=debug"]
    depends_on:
      - redis
